### PR TITLE
Add flag `--excludePackagesStartingWith [list]` 

### PR DESCRIPTION
**Pull request by rhl2401**
Added a way to exclude packages matching a given string. This is useful for excluding all packages form a specifc vendor or all internal packages that might be prefixed with a specific string, like `@<company>/<packagename>`which can be excluded alltogether with this flag: `--excludePackagesStartingWith '@<company>'` instead of adding **all** packages made by this company to the existing flag `--excludePackages`

@RSeidelsohn

### CODE REVIEW

**Comment by RSeidelsohn** [comment]
Thanks a lot for your contribution!

**Comment by rhl2401** [comment]
Thanks for merging and keeping the repo active!

**Comment by rhl2401** [comment]
@RSeidelsohn Are you planning on publishing on the NPM feed soon aswell? Thank you!

**Comment by eugene1g** [comment]
@RSeidelsohn Would you please cut a fresh release to NPM with this feature? It's super useful to exclude internal company libs that we _know_ are good, without having to list them all individually (e.g., `--excludePackagesStartingWith="@myorg/"`)

**Comment by RSeidelsohn** [comment]
Dear @eugene1g, please be patient - I plan to do it on the upcoming weekend. I know it's a small thing to do, but I need to get my head around it first while working on my full-time job, so I want to be somewhat undistracted by other stuff. Sorry for it taking so long!

**Comment by RSeidelsohn** [comment]
@eugene1g , @rhl2401 , I have released the updated version yesterday, but then (all blame to me as I did not check this beforehand - I definitely should work on this repo more often) discovered a bug in the `excludePackagesStartingWith` function when using more than one string to exclude. This is now also fixed and released as `v3.2.1`.

**Pull request merged**
