### PR TITLE
Support zero parity license for husky module

### PR DESCRIPTION
**Pull request by gugu**

### CODE REVIEW

**Comment by Ephigenia** [comment]
Just tested this using `--summary` and "Zero Parity" gets detected and listed properly.

**Comment by gugu** [comment]
@Ephigenia do you mean it works with my PR or does it work correctly without my PR for you?

**Comment by Ephigenia** [comment]
@gugu sorry for being not specific enough. It works with your PR. Doesn't work without your PR 😃

**Comment by gugu** [comment]
Thanks for checking!

**Comment by gugu** [comment]
@RSeidelsohn can you please check this PR. Currently husky is the module community needs to be aware of (they changed their license to a dangerous in the major version)

**Review by RSeidelsohn — APPROVED** [review]
Looks good, thanks a lot for your input!

**Pull request merged**
